// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CargoExpress.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "wip")]
    public partial class TS02_RegistrationOfANewTripFeature : object, Xunit.IClassFixture<TS02_RegistrationOfANewTripFeature.FixtureData>, System.IDisposable
    {

        private static TechTalk.SpecFlow.ITestRunner testRunner;

        private string[] _featureTags = new string[] {
                "wip"};

        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "TS02_RegistroNuevoViaje.feature"
#line hidden

        public TS02_RegistrationOfANewTripFeature(TS02_RegistrationOfANewTripFeature.FixtureData fixtureData, CargoExpress_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }

        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "TS02 - Registration of a new trip", "    As a logistics management entrepreneur, I want to register the data of a ne" +
                    "w trip to have a saved record and show transparency to my clients.", ProgrammingLanguage.CSharp, new string[] {
                        "wip"});
            testRunner.OnFeatureStart(featureInfo);
        }

        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        public virtual void TestInitialize()
        {
        }

        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }

        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }

        [Xunit.SkippableFactAttribute(DisplayName="Register a new trip successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "TS02 - Registration of a new trip")]
        [Xunit.TraitAttribute("Description", "Register a new trip successfully")]
        [Xunit.TraitAttribute("Category", "TS02")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Trips")]
        [Xunit.TraitAttribute("Category", "POST")]
        public virtual void RegisterANewTripSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "TS02",
                    "API",
                    "Trips",
                    "POST"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register a new trip successfully", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
        testRunner.Given("the entrepreneur has access to the API documentation and the necessary credentials for integration", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method",
                            "Body"});
                table1.AddRow(new string[] {
                            "/api/v1/trips",
                            "POST",
                            "{\"name\": \"Lima to Callao\", \"type\": \"Electronics\", \"weight\": 100, \"addressFrom\": \"Av. Lima 123\", \"scheduledDepartureDate\": \"2024-01-01T09:00:00\", \"addressTo\": \"Av. Peru 456\", \"scheduledArrivalDate\": \"2024-01-01T12:00:00\", \"driverId\": 1, \"vehicleId\": 1, \"clientId\": 1, \"entrepreneurId\": 1}"});
#line 8
        testRunner.When("the entrepreneur sends a POST request with the trip data to the API", ((string)(null)), table1, "When ");
#line hidden
#line 11
        testRunner.Then("the API responds with status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
        testRunner.And("the trip is correctly added to the database", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }

        [Xunit.SkippableFactAttribute(DisplayName="Get registered trip information")]
        [Xunit.TraitAttribute("FeatureTitle", "TS02 - Registration of a new trip")]
        [Xunit.TraitAttribute("Description", "Get registered trip information")]
        [Xunit.TraitAttribute("Category", "TS02")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Trips")]
        [Xunit.TraitAttribute("Category", "GET")]
        public virtual void GetRegisteredTripInformation()
        {
            string[] tagsOfScenario = new string[] {
                    "TS02",
                    "API",
                    "Trips",
                    "GET"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get registered trip information", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 15
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 16
        testRunner.Given("the entrepreneur has access to the API documentation and the necessary credentials for integration", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 17
        testRunner.And("there is a registered trip with ID 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method"});
                table2.AddRow(new string[] {
                            "/api/v1/trips/1",
                            "GET"});
#line 18
        testRunner.When("the entrepreneur sends a GET request to the API to obtain the information of a specific trip", ((string)(null)), table2, "When ");
#line hidden
#line 21
        testRunner.Then("the API responds with status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
        testRunner.And("returns the requested trip data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }

        [Xunit.SkippableFactAttribute(DisplayName="Error registering trip with invalid data")]
        [Xunit.TraitAttribute("FeatureTitle", "TS02 - Registration of a new trip")]
        [Xunit.TraitAttribute("Description", "Error registering trip with invalid data")]
        [Xunit.TraitAttribute("Category", "TS02")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Trips")]
        [Xunit.TraitAttribute("Category", "Error")]
        public virtual void ErrorRegisteringTripWithInvalidData()
        {
            string[] tagsOfScenario = new string[] {
                    "TS02",
                    "API",
                    "Trips",
                    "Error"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Error registering trip with invalid data", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 25
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
        testRunner.Given("the entrepreneur has access to the API documentation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method",
                            "Body"});
                table3.AddRow(new string[] {
                            "/api/v1/trips",
                            "POST",
                            "{\"name\": \"\", \"type\": \"\", \"weight\": -1, \"entrepreneurId\": 0}"});
#line 27
        testRunner.When("the entrepreneur sends a POST request with invalid trip data", ((string)(null)), table3, "When ");
#line hidden
#line 30
        testRunner.Then("the API responds with status code 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 31
        testRunner.And("returns a validation error message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }

        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {

            public FixtureData()
            {
                TS02_RegistrationOfANewTripFeature.FeatureSetup();
            }

            void System.IDisposable.Dispose()
            {
                TS02_RegistrationOfANewTripFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
