// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CargoExpress.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "wip")]
    public partial class TS07_ViewingTripDetailsFeature : object, Xunit.IClassFixture<TS07_ViewingTripDetailsFeature.FixtureData>, System.IDisposable
    {

        private static TechTalk.SpecFlow.ITestRunner testRunner;

        private string[] _featureTags = new string[] {
                "wip"};

        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;

#line 1 "TS07_VisualizacionDetallesViaje.feature"
#line hidden

        public TS07_ViewingTripDetailsFeature(TS07_ViewingTripDetailsFeature.FixtureData fixtureData, CargoExpress_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }

        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "TS07 - Viewing trip details", "    As a logistics management entrepreneur, I want to access specific details ab" +
                    "out the delivery of my shipment to have a complete understanding of the delivery process.", ProgrammingLanguage.CSharp, new string[] {
                        "wip"});
            testRunner.OnFeatureStart(featureInfo);
        }

        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }

        public virtual void TestInitialize()
        {
        }

        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }

        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }

        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }

        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }

        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }

        [Xunit.SkippableFactAttribute(DisplayName="View complete trip details by ID")]
        [Xunit.TraitAttribute("FeatureTitle", "TS07 - Viewing trip details")]
        [Xunit.TraitAttribute("Description", "View complete trip details by ID")]
        [Xunit.TraitAttribute("Category", "TS07")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Trips")]
        [Xunit.TraitAttribute("Category", "GET")]
        public virtual void ViewCompleteTripDetailsByID()
        {
            string[] tagsOfScenario = new string[] {
                    "TS07",
                    "API",
                    "Trips",
                    "GET"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View complete trip details by ID", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
        testRunner.Given("the entrepreneur has access to the API documentation and the necessary credentials for integration", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
        testRunner.And("there is a registered trip with ID 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method"});
                table1.AddRow(new string[] {
                            "/api/v1/trips/1",
                            "GET"});
#line 9
        testRunner.When("the entrepreneur sends a GET request to obtain the complete details of a trip", ((string)(null)), table1, "When ");
#line hidden
#line 12
        testRunner.Then("the API responds with status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 13
        testRunner.And("returns the complete trip details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }

        [Xunit.SkippableFactAttribute(DisplayName="View ongoing trip information for a trip")]
        [Xunit.TraitAttribute("FeatureTitle", "TS07 - Viewing trip details")]
        [Xunit.TraitAttribute("Description", "View ongoing trip information for a trip")]
        [Xunit.TraitAttribute("Category", "TS07")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Trips")]
        [Xunit.TraitAttribute("Category", "GET")]
        public virtual void ViewOngoingTripInformationForATrip()
        {
            string[] tagsOfScenario = new string[] {
                    "TS07",
                    "API",
                    "Trips",
                    "GET"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View ongoing trip information for a trip", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 16
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 17
        testRunner.Given("the entrepreneur has access to the API documentation and the necessary credentials for integration", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 18
        testRunner.And("there is a registered ongoing trip linked to trip with ID 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method"});
                table2.AddRow(new string[] {
                            "/api/v1/trips/1/ongoing-trips",
                            "GET"});
#line 19
        testRunner.When("the entrepreneur sends a GET request to obtain the ongoing trip information", ((string)(null)), table2, "When ");
#line hidden
#line 22
        testRunner.Then("the API responds with status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
        testRunner.And("returns the ongoing trip data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }

        [Xunit.SkippableFactAttribute(DisplayName="Error viewing trip details with nonexistent ID")]
        [Xunit.TraitAttribute("FeatureTitle", "TS07 - Viewing trip details")]
        [Xunit.TraitAttribute("Description", "Error viewing trip details with nonexistent ID")]
        [Xunit.TraitAttribute("Category", "TS07")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Trips")]
        [Xunit.TraitAttribute("Category", "Error")]
        public virtual void ErrorViewingTripDetailsWithNonexistentID()
        {
            string[] tagsOfScenario = new string[] {
                    "TS07",
                    "API",
                    "Trips",
                    "Error"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Error viewing trip details with nonexistent ID", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 26
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 27
        testRunner.Given("the entrepreneur has access to the API documentation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method"});
                table3.AddRow(new string[] {
                            "/api/v1/trips/999",
                            "GET"});
#line 28
        testRunner.When("the entrepreneur sends a GET request for a trip that does not exist", ((string)(null)), table3, "When ");
#line hidden
#line 31
        testRunner.Then("the API responds with status code 404", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
        testRunner.And("returns a not found error message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }

        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {

            public FixtureData()
            {
                TS07_ViewingTripDetailsFeature.FeatureSetup();
            }

            void System.IDisposable.Dispose()
            {
                TS07_ViewingTripDetailsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
