// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CargoExpress.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "wip")]
    public partial class TS14_LoginFeature : object, Xunit.IClassFixture<TS14_LoginFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "wip"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TS14_Login.feature"
#line hidden
        
        public TS14_LoginFeature(TS14_LoginFeature.FixtureData fixtureData, CargoExpress_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "TS14 - Login", "    As a user, I want to access my registered account to use the application\'s fu" +
                    "nctions.", ProgrammingLanguage.CSharp, new string[] {
                        "wip"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login with valid credentials successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "TS14 - Login")]
        [Xunit.TraitAttribute("Description", "Login with valid credentials successfully")]
        [Xunit.TraitAttribute("Category", "TS14")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Authentication")]
        [Xunit.TraitAttribute("Category", "POST")]
        public virtual void LoginWithValidCredentialsSuccessfully()
        {
            string[] tagsOfScenario = new string[] {
                    "TS14",
                    "API",
                    "Authentication",
                    "POST"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Login with valid credentials successfully", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
        testRunner.Given("the user has a registered account in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method",
                            "Body"});
                table40.AddRow(new string[] {
                            "/api/v1/authentication/sign-in",
                            "POST",
                            "{\"username\": \"existingUser\", \"password\": \"SecurePass1!\"}"});
#line 8
        testRunner.When("the user sends a POST request with their login credentials to the API", ((string)(null)), table40, "When ");
#line hidden
#line 11
        testRunner.Then("the API responds with status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
        testRunner.And("returns a valid authentication token", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get user role after login")]
        [Xunit.TraitAttribute("FeatureTitle", "TS14 - Login")]
        [Xunit.TraitAttribute("Description", "Get user role after login")]
        [Xunit.TraitAttribute("Category", "TS14")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Authentication")]
        [Xunit.TraitAttribute("Category", "GET")]
        public virtual void GetUserRoleAfterLogin()
        {
            string[] tagsOfScenario = new string[] {
                    "TS14",
                    "API",
                    "Authentication",
                    "GET"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get user role after login", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 15
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 16
        testRunner.Given("the user has a registered account in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 17
        testRunner.And("there is a registered user with ID 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method"});
                table41.AddRow(new string[] {
                            "/api/v1/users/1/role",
                            "GET"});
#line 18
        testRunner.When("the user sends a GET request to obtain their role information", ((string)(null)), table41, "When ");
#line hidden
#line 21
        testRunner.Then("the API responds with status code 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
        testRunner.And("returns the user role information", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Error login with invalid credentials")]
        [Xunit.TraitAttribute("FeatureTitle", "TS14 - Login")]
        [Xunit.TraitAttribute("Description", "Error login with invalid credentials")]
        [Xunit.TraitAttribute("Category", "TS14")]
        [Xunit.TraitAttribute("Category", "API")]
        [Xunit.TraitAttribute("Category", "Authentication")]
        [Xunit.TraitAttribute("Category", "Error")]
        public virtual void ErrorLoginWithInvalidCredentials()
        {
            string[] tagsOfScenario = new string[] {
                    "TS14",
                    "API",
                    "Authentication",
                    "Error"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Error login with invalid credentials", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 25
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 26
        testRunner.Given("the user has access to the API documentation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "Endpoint",
                            "Method",
                            "Body"});
                table42.AddRow(new string[] {
                            "/api/v1/authentication/sign-in",
                            "POST",
                            "{\"username\": \"wrongUser\", \"password\": \"wrong\"}"});
#line 27
        testRunner.When("the user sends a POST request with invalid login credentials", ((string)(null)), table42, "When ");
#line hidden
#line 30
        testRunner.Then("the API responds with status code 401", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 31
        testRunner.And("returns an authentication error message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TS14_LoginFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TS14_LoginFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
